---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: podinfo
  namespace: flux-system
spec:
  filterTags:
    extract: ""
    pattern: dev-*
  imageRepositoryRef:
    name: podinfo
  policy:
    alphabetical:
      order: asc
