---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: podinfo
  namespace: flux-system
spec:
  filterTags:
    extract: $ts
    pattern: ^dev-(?P<ts>.*)
  imageRepositoryRef:
    name: podinfo
  policy:
    numerical:
      order: asc
